In [4]:
import pandas as pd
import requests
import re

# Fetch all Pokemon species names from PokeAPI
print("Fetching all Pokemon species from PokeAPI...")
response = requests.get("https://pokeapi.co/api/v2/pokemon-species?limit=1500")
species_data = response.json()['results']

# Map API names to card-style names
SPECIAL_NAMES = {
    'nidoran-f': 'Nidoran \u2640', 'nidoran-m': 'Nidoran \u2642',
    'mr-mime': 'Mr. Mime', 'mime-jr': 'Mime Jr.', 'mr-rime': 'Mr. Rime',
    'ho-oh': 'Ho-Oh', 'porygon-z': 'Porygon-Z', 'type-null': 'Type: Null',
    'jangmo-o': 'Jangmo-o', 'hakamo-o': 'Hakamo-o', 'kommo-o': 'Kommo-o',
    'tapu-koko': 'Tapu Koko', 'tapu-lele': 'Tapu Lele',
    'tapu-bulu': 'Tapu Bulu', 'tapu-fini': 'Tapu Fini',
    'wo-chien': 'Wo-Chien', 'chien-pao': 'Chien-Pao',
    'ting-lu': 'Ting-Lu', 'chi-yu': 'Chi-Yu',
    'great-tusk': 'Great Tusk', 'scream-tail': 'Scream Tail',
    'brute-bonnet': 'Brute Bonnet', 'flutter-mane': 'Flutter Mane',
    'slither-wing': 'Slither Wing', 'sandy-shocks': 'Sandy Shocks',
    'iron-treads': 'Iron Treads', 'iron-bundle': 'Iron Bundle',
    'iron-hands': 'Iron Hands', 'iron-jugulis': 'Iron Jugulis',
    'iron-moth': 'Iron Moth', 'iron-thorns': 'Iron Thorns',
    'roaring-moon': 'Roaring Moon', 'iron-valiant': 'Iron Valiant',
    'walking-wake': 'Walking Wake', 'iron-leaves': 'Iron Leaves',
    'gouging-fire': 'Gouging Fire', 'raging-bolt': 'Raging Bolt',
    'iron-boulder': 'Iron Boulder', 'iron-crown': 'Iron Crown',
    'farfetchd': "Farfetch'd", 'sirfetchd': "Sirfetch'd",
    'flabebe': 'Flab\u00e9b\u00e9',
}

../data/pokemon_names = set()
for entry in species_data:
    api_name = entry['name']
    if api_name in SPECIAL_NAMES:
        card_name = SPECIAL_NAMES[api_name]
    else:
        card_name = api_name.replace('-', ' ').title()
    pokemon_names.add(card_name)

# Add common card name variations
../data/pokemon_names.update(['Nidoran', "Farfetch'd", 'Ho-Oh', 'Mime Jr', 'Unown'])

print(f"Loaded {len(pokemon_names)} Pokemon species names")

Fetching all Pokemon species from PokeAPI...
Loaded 1027 Pokemon species names

In [5]:
# Build one regex matching any Pokemon name (longest first to avoid partial matches)
../data/pokemon_pattern = re.compile(
    '|'.join(re.escape(name) for name in sorted(pokemon_names, key=len, reverse=True)),
    re.IGNORECASE,
)


def is_pokemon(species_str):
    if not species_str or pd.isna(species_str):
        return False
    return bool(pokemon_pattern.search(str(species_str)))


# Load and filter
df = pd.read_csv("../data/pokemon_all_sorted.csv")
print(f"Total cards before cleaning: {len(df)}")

mask = df['Species'].apply(is_pokemon)
removed = df[~mask]

print(f"\nRemoving {len(removed)} non-Pokemon entries. Unique species removed:")
for species in sorted(removed['Species'].unique()):
    print(f"  \u2717 {species}")

df_clean = df[mask].reset_index(drop=True)
df_clean.to_csv("../data/pokemon_all_cleaned.csv", index=False)
print(f"\nKept {len(df_clean)} real Pokemon cards \u2192 saved to 'pokemon_all_cleaned.csv'")
df_clean.head(10)

Total cards before cleaning: 4395

Removing 581 non-Pokemon entries. Unique species removed:
  ✗ 2 Pack Blister
  ✗ 2-Pack Blister
  ✗ 2-Pack Blister Pack
  ✗ 2-Player Starter Set
  ✗ 2025 Holiday Calendar Box
  ✗ 2025 Pokemon Collector Chest
  ✗ Ancient Ruins
  ✗ Apricorn Forest
  ✗ Apricorn Maker
  ✗ Balloon Berry
  ✗ Battle City
  ✗ Battle Deck
  ✗ Beeheyem
  ✗ Bill
  ✗ Bill's Maintenance
  ✗ Blackout
  ✗ Blanche
  ✗ Blister Pack
  ✗ Boost Energy
  ✗ Booster Box
  ✗ Booster Pack
  ✗ Boss's Orders
  ✗ Bounce Energy
  ✗ Broken Ground Gym
  ✗ Brushfire
  ✗ Buffer Piece
  ✗ Buried Fossil
  ✗ Candela
  ✗ Challenge
  ✗ Champion's Festival
  ✗ Champions Festival
  ✗ Championship Arena
  ✗ Cheren
  ✗ Chinese New Year Collection Box
  ✗ Computer Error
  ✗ Computer Search
  ✗ Copycat
  ✗ Counterattack Claws
  ✗ Crystal Energy
  ✗ Crystal Shard
  ✗ Cyclone Energy
  ✗ Darkness Cube 01
  ✗ Darkness Energy
  ✗ Defender
  ✗ Desert Shaman
  ✗ Devolution Spray
  ✗ Double Colorless Energy
  ✗ Dual Ball
  ✗ EXP. ALL
  ✗ Electric Garden Theme Deck
  ✗ Energy Amplifier
  ✗ Energy Charge
  ✗ Energy Removal
  ✗ Energy Removal 2
  ✗ Energy Restore
  ✗ Energy Retrieval
  ✗ Energy Search
  ✗ Energy Stadium
  ✗ Energy Switch
  ✗ Eon Ticket
  ✗ Espthra
  ✗ Evolving Powers Premium Collection
  ✗ Factory Sealed Paldea Adventure Chest
  ✗ Fall 2023 Collector Chest
  ✗ Fall 2025 Collector Chest
  ✗ Fanfare Perayaan
  ✗ Fast Ball
  ✗ Fighting Cube 01
  ✗ Fighting Energy
  ✗ Fire Cube 01
  ✗ Fire Energy
  ✗ Fisherman
  ✗ Forest Guardian
  ✗ Friend Ball
  ✗ Full Heal
  ✗ Full Heal Energy
  ✗ Gardevior
  ✗ Grass Cube 01
  ✗ Grass Energy
  ✗ Gust of Wind
  ✗ Gym Badge
  ✗ Heal Energy
  ✗ Heal Powder
  ✗ Healing Berry
  ✗ Holiday Calendar Box 2022
  ✗ Holiday Calendar Box 2023
  ✗ Holiday Calendar Box 2024
  ✗ Holliday Calendar Box 2025
  ✗ Holon Energy FF
  ✗ Holon Energy GL
  ✗ Holon Energy WP
  ✗ Holon Legacy
  ✗ Holon Mentor
  ✗ Hyper Potion
  ✗ Imposter Professor Oak
  ✗ Imposter Professor Oak's Invention
  ✗ Iono
  ✗ Iono Premium Tournament Collection Box
  ✗ Ishihara
  ✗ Island Hermit
  ✗ Item Finder
  ✗ Juggler
  ✗ Karen
  ✗ Klara
  ✗ Lady Outing
  ✗ Lass
  ✗ Legendary Warriors Premium Collection Box
  ✗ Lightning Cube 01
  ✗ Lightning Energy
  ✗ Lillie
  ✗ Lillie Premium Tournament Collection Box
  ✗ Lucky Stadium
  ✗ Lure Ball
  ✗ Magnifier
  ✗ Mail from Bill
  ✗ Maintenance
  ✗ Manhole
  ✗ Marnie
  ✗ Mary's Impulse
  ✗ Master Ball
  ✗ Meagearna
  ✗ Memory Berry
  ✗ Metal Cube 01
  ✗ Metal Energy
  ✗ Metal Stacking Tin
  ✗ Meteor Falls
  ✗ Miracle Energy
  ✗ Miracle Sphere
  ✗ Mirage Stadium
  ✗ Moo-Moo Milk
  ✗ Mr. Stone's Project
  ✗ Multi Technical Machine 01
  ✗ Mysterious Fossil
  ✗ Mystery Plate
  ✗ Mystery Zone
  ✗ N
  ✗ No. 3 Trainer
  ✗ Old Rod
  ✗ Oracle
  ✗ Overgrowth
  ✗ Paldea Friends Mini Tins 5-Pack
  ✗ Paradise Resort
  ✗ Paradox Clash Tin
  ✗ Paradox Destinies Tin
  ✗ Paradox Fury Premium Collection
  ✗ Perona
  ✗ Picnicker
  ✗ Play! Prize Pack Series 1
  ✗ Play! Prize Pack Series 2
  ✗ Play! Prize Pack Series 3
  ✗ PlusPower
  ✗ Poke Ball Tin
  ✗ Poke Ball Tin Display
  ✗ Pokedex
  ✗ Pokemon Breeder
  ✗ Pokemon Center
  ✗ Pokemon Day 2026 Collection Box
  ✗ Pokemon Fan Club
  ✗ Pokemon Flute
  ✗ Pokemon Nurse
  ✗ Pokemon Park
  ✗ Pokemon Personality Test
  ✗ Pokemon Reversal
  ✗ Pokemon Tower
  ✗ Pokemon Trader
  ✗ Potion
  ✗ Potion Energy
  ✗ Power Charge
  ✗ Power Plant
  ✗ Professor Burnet
  ✗ Professor Cozmo's Discovery
  ✗ Professor Elm's Training Method
  ✗ Professor Oak
  ✗ Professor Oak's Research
  ✗ Professor's Research
  ✗ Psychic Cube 01
  ✗ Psychic Energy
  ✗ Radio Tower
  ✗ Rainbow Energy
  ✗ Relic Hunter
  ✗ Retro Energy
  ✗ Revive
  ✗ Rival Battle Deck
  ✗ Sabrina & Brycen
  ✗ Scoop Up
  ✗ Scramble Energy
  ✗ Sealed Illustration Contest 2024
  ✗ Seer
  ✗ Slashing Legends Tin
  ✗ Space Center
  ✗ Spark
  ✗ Star Piece
  ✗ Starter Gift Box
  ✗ Strength Charm
  ✗ Super Energy Removal
  ✗ Super Energy Removal 2
  ✗ Super Potion
  ✗ Super Scoop Up
  ✗ Switch
  ✗ TV Reporter
  ✗ Team Rocket's Evil Deeds
  ✗ Tera Team Premium Collection
  ✗ The Boss's Way
  ✗ Thought Wave Machine
  ✗ Time Shard
  ✗ Town Volunteers
  ✗ Trainer's Toolkit 2025
  ✗ Traveling Salesman
  ✗ Treasures Of Ruin Stacking Tin
  ✗ Tropical Beach
  ✗ Tropical Tidal Wave
  ✗ Tropical Wind
  ✗ Underground Expedition
  ✗ Underground Lake
  ✗ Undersea Ruins
  ✗ V Battle Deck
  ✗ Victory Cup
  ✗ Victory Medal
  ✗ Warp Energy
  ✗ Warp Point
  ✗ Water Cube 01
  ✗ Water Energy
  ✗ Water energy
  ✗ Weakness Guard
  ✗ Zap

Kept 3814 real Pokemon cards → saved to 'pokemon_all_cleaned.csv'

,Set,Species,Card Name,Ungraded Price,Grade 9 Price,PSA 10 Price,Image URL
0,Promo,Gengar,Gengar [Prerelease Staff] #SWSH241,"$2,000.00","$3,218.83","$3,863.00",https://storage.googleapis.com/images.pricecha...
1,Promo,Gengar,Mega Gengar EX #XY166,$138.94,$616.10,"$6,156.60",https://storage.googleapis.com/images.pricecha...
2,Promo,Gengar,Gengar #SWSH052,$83.86,$149.44,"$1,970.12",https://storage.googleapis.com/images.pricecha...
3,Promo,Gengar,Gengar #SWSH241,$27.27,$46.20,$325.00,https://storage.googleapis.com/images.pricecha...
4,Promo,_____'s Mew,_____'s Mew [Play] #13,$850.00,"$1,550.00","$2,000.00",https://storage.googleapis.com/images.pricecha...
5,Promo,Pikachu with Grey Felt Hat,Pikachu with Grey Felt Hat #85,$846.46,$865.66,"$2,543.59",https://storage.googleapis.com/images.pricecha...
6,Promo,Tin: Pikachu & Zekrom,Tag Team Tin: Pikachu & Zekrom GX,$793.67,NaN,NaN,https://storage.googleapis.com/images.pricecha...
7,Promo,Special Delivery Bidoof,Special Delivery Bidoof #SWSH177,$581.43,$480.00,"$2,500.00",https://storage.googleapis.com/images.pricecha...
8,Promo,Pikachu,Pikachu [1st Edition Error] #1,$545.00,"$1,544.00",NaN,https://storage.googleapis.com/images.pricecha...
9,Promo,Pikachu,Pikachu [Asia Championship] #101,$317.54,$455.99,$775.00,https://storage.googleapis.com/images.pricecha...

In [6]:
df = pd.read_csv("../data/pokemon_all_cleaned.csv")
print(f"Cards before name cleaning: {len(df)}")

# Step 1: Remove sealed products (Boxes, Tins, Collections, Decks — not actual cards)
product_pattern = re.compile(
    r'\b(Box|Tin|Collection|Deck|Premium|Chest|Bundle|Lunchbox|Mini Tin|V-UNION Special)\b',
    re.IGNORECASE,
)
is_product = df['Species'].apply(lambda s: bool(product_pattern.search(str(s))) if pd.notna(s) else False)
print(f"\nRemoving {is_product.sum()} sealed product entries:")
for sp in sorted(df.loc[is_product, 'Species'].unique()):
    print(f"  \u2717 {sp}")
df = df[~is_product].reset_index(drop=True)


# Step 2: Clean species names to core Pokemon name
def clean_species(name):
    if pd.isna(name):
        return name
    s = str(name).strip().strip('"')

    # "_____'s Mew" → "Mew", "Ash's Pikachu" → "Pikachu"
    s = re.sub(r"^[\w_]+['\u2019]s\s+", "", s)

    # "Catch Mew" → "Mew"
    s = re.sub(r'^Catch\s+', '', s)

    # For "&" Tag Team entries, clean each part individually
    if ' & ' in s:
        parts = [clean_single(p.strip()) for p in s.split(' & ')]
        return ' & '.join(parts)

    return clean_single(s)


def clean_single(s):
    # Strip regional prefixes
    s = re.sub(r'^(Alolan|Galarian|Hisuian|Paldean|Bloodmoon|Ash-)\s*', '', s)

    # Strip card variant prefixes
    s = re.sub(r'^(Dark|Light|Shining|Crystal|Ancient|Armored|Shadow Rider|Shadow|Flying|Surfing|Birthday|Black|White)\s+', '', s)

    # Strip suffixes: V, VMAX, VSTAR, GX, EX, LV.X, G, C, X, ex, V-UNION
    # Run twice to catch "G LV.X" → strip G → strip LV.X
    for _ in range(2):
        s = re.sub(r'\s+(V|VMAX|VSTAR|GX|EX|LV\.X|G|C|X|V-UNION|ex)\s*$', '', s)

    # Fix concatenated "ex" from scraping (e.g. "Alakazamex" → "Alakazam")
    if s.endswith('ex') and len(s) > 4 and s[:-2].isalpha():
        s = s[:-2]

    # "Pokemon Treasure Chest ..." or "Pokemon ..." prefix
    s = re.sub(r'^Pokemon\s+', '', s)

    return s.strip()


# Apply cleaning and track changes
df['Species_Original'] = df['Species']
df['Species'] = df['Species'].apply(clean_species)

# Show all changes
changes = df[df['Species'] != df['Species_Original']][['Species_Original', 'Species']].drop_duplicates()
print(f"\nCleaned {len(changes)} unique species names:")
for _, row in changes.sort_values('Species_Original').iterrows():
    print(f"  {row['Species_Original']} \u2192 {row['Species']}")

df = df.drop(columns=['Species_Original'])
df.to_csv("../data/pokemon_all_cleaned.csv", index=False)
print(f"\nSaved {len(df)} cards to 'pokemon_all_cleaned.csv'")
df.head(10)

Cards before name cleaning: 3814

Removing 66 sealed product entries:
  ✗ Annihilape Box
  ✗ Archaludon Box
  ✗ Azure Legends Tin: Dialga
  ✗ Azure Legends Tin: Kyogre
  ✗ Battle Deck: Diancie
  ✗ Black Kyurem Box
  ✗ Blaziken & Volcanion Premium Collection
  ✗ Celebi & Venusaur Tin
  ✗ Charizard Special Collection Box
  ✗ Charizard Super Premium Collection Box
  ✗ Charizard Tin
  ✗ Darkrai Premium Collection Box
  ✗ Deluxe Battle Deck: Zapdos
  ✗ Deoxys & Battle Box
  ✗ Eevee & Snorlax Tin
  ✗ Eevee Pokemon Treasure Chest Tin
  ✗ Galarian Rapidash V Box
  ✗ Grafaiai Box
  ✗ Greninja & Kingdra Special Collection Box
  ✗ Greninja V-UNION Special Collection
  ✗ Heavy Hitters Premium Collection: Lucario V & Tyranitar V
  ✗ Hidden Potential Tin: Giratina V
  ✗ Houndstone Box
  ✗ Hydreigon & Dragapult Premium Collection
  ✗ Incineroar And Torterra Special Collection
  ✗ Iono's Bellibolt Premium Collection Box
  ✗ Iron Bundle
  ✗ Iron Valiant Box
  ✗ Kangaskhan Box
  ✗ Kanto Friends Mini Tin: Bulbasaur
  ✗ Kanto Power Mini Tin: Charizard
  ✗ Kanto Power Mini Tin: Dragonite
  ✗ Kanto Power Mini Tin: Mewtwo
  ✗ Kanto Power Mini Tin: Pikachu
  ✗ Kleavor Premium Collection Box
  ✗ Latias Box
  ✗ League Battle Deck: Charizard
  ✗ League Battle Deck: Gardevoir
  ✗ League Battle Deck: Mew
  ✗ League Battle Deck: Miraidon
  ✗ Lucario Special Collection
  ✗ Lugia & Latias Premium Collection
  ✗ Mabosstiff Box
  ✗ Melmetal Box
  ✗ Meowth Special Collection Box
  ✗ Mew V Box
  ✗ Ogerpon Stacking Tin
  ✗ Palafin Box
  ✗ Reshiram Box
  ✗ Roaring Moon Box
  ✗ Salamence & Reshiram Premium Collection
  ✗ Sealed Battle Deck: Gengar
  ✗ Sealed Cynthia's Garchomp Premium Collection
  ✗ Shaymin Premium Collection
  ✗ Snorlax & Blissey Special Collection
  ✗ Team Rocket's Moltres Ultra Premium Collection Box
  ✗ Terapagos Ultra Premium Collection Box
  ✗ Tin: Pikachu & Zekrom
  ✗ Trainer's Legendary Box: Ho-Oh
  ✗ Tyranitar Lunchbox Chest Tin
  ✗ V-Union Special Collection - Mewtwo
  ✗ Venusaur Premium Collection
  ✗ Zacian V-UNION Special Collection Box
  ✗ Zeraora & Battle Box

Cleaned 217 unique species names:
  Alakazam V → Alakazam
  Alakazamex → Alakazam
  Alolan Exeggutor V → Exeggutor
  Alolan Marowak → Marowak
  Alolan Meowth → Meowth
  Alolan Ninetales → Ninetales
  Alolan Raichu → Raichu
  Alolan Sandslash → Sandslash
  Ancient Mew → Mew
  Arceus LV.X → Arceus
  Arceus V → Arceus
  Armored Mewtwo → Mewtwo
  Ash's Pikachu → Pikachu
  Ash-Greninja → Greninja
  Birthday Pikachu → Pikachu
  Black Kyurem → Kyurem
  Blastoise V → Blastoise
  Bloodmoon Ursaluna → Ursaluna
  Boltund V → Boltund
  Carnivine G → Carnivine
  Catch Mew → Mew
  Charizard G LV.X → Charizard
  Charizard V → Charizard
  Charizard X → Charizard
  Cinderace V → Cinderace
  Copperajah V → Copperajah
  Corviknight V → Corviknight
  Cramorant V → Cramorant
  Crobat V → Crobat
  Cynthia's Garchomp → Garchomp
  Dark Ampharos → Ampharos
  Dark Ariados → Ariados
  Dark Blastoise → Blastoise
  Dark Crobat → Crobat
  Dark Croconaw → Croconaw
  Dark Donphan → Donphan
  Dark Dragonair → Dragonair
  Dark Dragonite → Dragonite
  Dark Espeon → Espeon
  Dark Exeggutor → Exeggutor
  Dark Feraligatr → Feraligatr
  Dark Flaaffy → Flaaffy
  Dark Forretress → Forretress
  Dark Gengar → Gengar
  Dark Haunter → Haunter
  Dark Houndoom → Houndoom
  Dark Magcargo → Magcargo
  Dark Octillery → Octillery
  Dark Omanyte → Omanyte
  Dark Omastar → Omastar
  Dark Persian → Persian
  Dark Porygon2 → Porygon2
  Dark Pupitar → Pupitar
  Dark Quilava → Quilava
  Dark Raichu → Raichu
  Dark Scizor → Scizor
  Dark Slowbro → Slowbro
  Dark Slowking → Slowking
  Dark Typhlosion → Typhlosion
  Dark Tyranitar → Tyranitar
  Dark Ursaring → Ursaring
  Dark Vaporeon → Vaporeon
  Dark Wartortle → Wartortle
  Dark Wigglytuff → Wigglytuff
  Darkrai LV.X → Darkrai
  Deoxys V → Deoxys
  Dialga LV.X → Dialga
  Dragapult V → Dragapult
  Dragonite V → Dragonite
  Dubwool V → Dubwool
  Eevee V → Eevee
  Eldegoss V → Eldegoss
  Empoleon LV.X → Empoleon
  Empoleon V → Empoleon
  Espeon V → Espeon
  Eternatus V → Eternatus
  Flareon V → Flareon
  Flying Pikachu → Pikachu
  Galarian Articuno → Articuno
  Galarian Moltres → Moltres
  Galarian Mr. Rime → Mr. Rime
  Galarian Obstagoon → Obstagoon
  Galarian Ponyta → Ponyta
  Galarian Rapidash V → Rapidash
  Galarian Sirfetch'd V → Sirfetch'd
  Galarian Slowpoke → Slowpoke
  Galarian Zapdos → Zapdos
  Gallade V → Gallade
  Garchomp C → Garchomp
  Garchomp C LV.X → Garchomp
  Gardevoir V → Gardevoir
  Giratina LV.X → Giratina
  Giratina V → Giratina
  Glaceon V → Glaceon
  Grimmsnarl V → Grimmsnarl
  Hatterene V → Hatterene
  Heatran LV.X → Heatran
  Hisuian Arcanine → Arcanine
  Hisuian Basculegion → Basculegion
  Hisuian Basculin → Basculin
  Hisuian Decidueye V → Decidueye
  Hisuian Electrode V → Electrode
  Hisuian Samurott → Samurott
  Hisuian Samurott V → Samurott
  Hisuian Typhlosion V → Typhlosion
  Hisuian Zoroark → Zoroark
  Hisuian Zoroark V → Zoroark
  Hoopa V → Hoopa
  Hop's Snorlax → Snorlax
  Hop's Zacian → Zacian
  Ice Rider Calyrex V → Ice Rider Calyrex
  Infernape LV.X → Infernape
  Infernape V → Infernape
  Inteleon V → Inteleon
  Iono's Bellibolt → Bellibolt
  Iono's Kilowattrel → Kilowattrel
  Jirachi V → Jirachi
  Jolteon V → Jolteon
  Kleavor V → Kleavor
  Lance's Charizard V → Charizard
  Leafeon V → Leafeon
  Light Arcanine → Arcanine
  Light Azumarill → Azumarill
  Light Dewgong → Dewgong
  Light Dragonair → Dragonair
  Light Dragonite → Dragonite
  Light Flareon → Flareon
  Light Golduck → Golduck
  Light Jolteon → Jolteon
  Light Lanturn → Lanturn
  Light Ledian → Ledian
  Light Machamp → Machamp
  Light Machoke → Machoke
  Light Ninetales → Ninetales
  Light Piloswine → Piloswine
  Light Slowbro → Slowbro
  Light Sunflora → Sunflora
  Light Togetic → Togetic
  Light Vaporeon → Vaporeon
  Light Venomoth → Venomoth
  Light Wigglytuff → Wigglytuff
  Lillie's Clefairy → Clefairy
  Lillie's Ribombee → Ribombee
  Lucario LV.X → Lucario
  Lucario V → Lucario
  Lugia V → Lugia
  Lumineon V → Lumineon
  Lycanroc V → Lycanroc
  Marnie's Morpeko → Morpeko
  Melmetal V → Melmetal
  Meowth V → Meowth
  Mewex → Mew
  Mewtwo LV.X → Mewtwo
  Mewtwo V → Mewtwo
  Morpeko V → Morpeko
  Morpeko V-UNION → Morpeko
  N's Darmanitan → Darmanitan
  N's Zekrom → Zekrom
  N's Zorua → Zorua
  Noivern V → Noivern
  Orbeetle V → Orbeetle
  Origin Forme Dialga V → Origin Forme Dialga
  Origin Forme Palkia V → Origin Forme Palkia
  Paldean Wooper → Wooper
  Palkia LV.X → Palkia
  Pikachu V → Pikachu
  Pikachu V-UNION → Pikachu
  Polteageist V → Polteageist
  Probopass G → Probopass
  Rapid Strike Urshifu V → Rapid Strike Urshifu
  Rayquaza C LV.X → Rayquaza
  Rayquaza V → Rayquaza
  Regidrago V → Regidrago
  Regieleki V → Regieleki
  Regigigas LV.X → Regigigas
  Rhyperior LV.X → Rhyperior
  Rillaboom V → Rillaboom
  Rocket's Raikou → Raikou
  Rotom V → Rotom
  Sabrina's Abra → Abra
  Shadow Lugia → Lugia
  Shadow Rider Calyrex V → Calyr
  Shaymin LV.X → Shaymin
  Shining Celebi → Celebi
  Shining Charizard → Charizard
  Shining Ho-Oh → Ho-Oh
  Shining Kabutops → Kabutops
  Shining Lugia → Lugia
  Shining Mewtwo → Mewtwo
  Shining Noctowl → Noctowl
  Shining Raichu → Raichu
  Shining Steelix → Steelix
  Shining Tyranitar → Tyranitar
  Single Strike Urshifu V → Single Strike Urshifu
  Steven's Beldum → Beldum
  Surfing Pikachu → Pikachu
  Sylveon V → Sylveon
  Torterra LV.X → Torterra
  Toxicroak G → Toxicroak
  Toxtricity V → Toxtricity
  Tyranitar V → Tyranitar
  Umbreon V → Umbreon
  Unown C → Unown
  Unown G → Unown
  Unown V → Unown
  Unown X → Unown
  Vaporeon V → Vaporeon
  Venusaur V → Venusaur
  Victini V → Victini
  Virizion V → Virizion
  White Kyurem → Kyurem
  Wigglytuffex → Wigglytuff
  Zacian V → Zacian
  Zamazenta V → Zamazenta
  Zapdosex → Zapdos
  Zeraora V → Zeraora
  _____'s Mew → Mew

Saved 3748 cards to 'pokemon_all_cleaned.csv'

,Set,Species,Card Name,Ungraded Price,Grade 9 Price,PSA 10 Price,Image URL
0,Promo,Gengar,Gengar [Prerelease Staff] #SWSH241,"$2,000.00","$3,218.83","$3,863.00",https://storage.googleapis.com/images.pricecha...
1,Promo,Gengar,Mega Gengar EX #XY166,$138.94,$616.10,"$6,156.60",https://storage.googleapis.com/images.pricecha...
2,Promo,Gengar,Gengar #SWSH052,$83.86,$149.44,"$1,970.12",https://storage.googleapis.com/images.pricecha...
3,Promo,Gengar,Gengar #SWSH241,$27.27,$46.20,$325.00,https://storage.googleapis.com/images.pricecha...
4,Promo,Mew,_____'s Mew [Play] #13,$850.00,"$1,550.00","$2,000.00",https://storage.googleapis.com/images.pricecha...
5,Promo,Pikachu with Grey Felt Hat,Pikachu with Grey Felt Hat #85,$846.46,$865.66,"$2,543.59",https://storage.googleapis.com/images.pricecha...
6,Promo,Special Delivery Bidoof,Special Delivery Bidoof #SWSH177,$581.43,$480.00,"$2,500.00",https://storage.googleapis.com/images.pricecha...
7,Promo,Pikachu,Pikachu [1st Edition Error] #1,$545.00,"$1,544.00",NaN,https://storage.googleapis.com/images.pricecha...
8,Promo,Pikachu,Pikachu [Asia Championship] #101,$317.54,$455.99,$775.00,https://storage.googleapis.com/images.pricecha...
9,Promo,Pikachu,Pikachu EX #XY124,$237.10,"$1,551.90","$7,946.07",https://storage.googleapis.com/images.pricecha...